trigger:
- main

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'AWS VM'
    runOptions: 'commands'
    commands: |
      chmod +x /home/ubuntu/poultry-deploy/deploy.sh
      /home/ubuntu/poultry-deploy/deploy.sh
    readyTimeout: '20000'